spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://119.29.56.63:3306/learning?characterEncoding=utf-8
  jpa:
    show-sql: true
server:
  context-path: /sell
